use_frameworks! :linkage => :static

platform :ios, '11.0'

target 'TCTracking_Example' do
  pod 'TCTracking', :git => 'https://github.com/phutttc/TCTracking'
  target 'TCTracking_Tests' do
    inherit! :search_paths
  end
end
